---
- name: Setup weed firewall
  firewalld:
    state: "enabled"
    port: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
  loop:
    - 9333/tcp
    - 19333/tcp
    - 9333/udp
    - 19333/udp
    - 8080/tcp
    - 18080/tcp
    - 8080/udp
    - 18080/udp
    - 9102/tcp
    - 9103/tcp
    - 16379/tcp
    - 6379/tcp
    - 26379/tcp

- name: Run redis
  import_tasks: redis.yml

- name: Flush handlers for Redis
  meta: flush_handlers

- name: Run seaweed
  import_tasks: seaweed.yml
