---
- name: Setup juice firewall
  firewalld:
    state: "enabled"
    port: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
  loop:
    - 9000/tcp
    - 9000/udp
    - 9001/tcp
    - 9001/udp
    - 16379/tcp
    - 6379/tcp
    - 26379/tcp

- name: Run minio
  import_tasks: minio.yml

- name: Run redis
  import_tasks: redis.yml

- name: Flush handlers for Redis
  meta: flush_handlers
