---
- name: Download minio
  get_url:
    url: "{{ minio_url }}"
    dest: "/tmp/{{ minio_rpm }}"
  notify:
    - Restart Minio Service

- name: Install minio
  dnf:
    name: "/tmp/{{ minio_rpm }}"
    state: present
    disable_gpg_check: true

- name: Add minio-user
  ansible.builtin.user:
    name: minio-user
    shell: /sbin/nologin

- name: Make minio directory
  file:
    owner: minio-user
    group: minio-user
    path: "/mnt/minio"
    state: directory
    mode: "0755"

- name: Template minio default env
  template:
    src: minio.env.j2
    dest: "/etc/default/minio"
    mode: 0644
    owner: minio-user
    group: minio-user
  notify: Restart Minio Service

- name: Deploy minio consul service
  copy:
    src: minio.hcl
    dest: /etc/consul.d/minio-consul.hcl
    mode: 0644
  notify:
    - Restart Consul Service
