---
- name: Install Redis
  dnf:
    name: redis
    state: present
- name: set vm.overcommit_memory
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: "1"
    state: present

- name: Deploy Redis Conf
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    mode: 0644
  notify:
    - Restart redis

- name: Deploy Sentinel Conf
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel.conf
    mode: 0644
  notify:
    - Restart sentinel
