---
- name: Install nomad
  ansible.builtin.dnf:
    name: nomad
    state: present

- name: Add Firewall rules for Nomad
  ansible.builtin.firewalld:
    state: "enabled"
    port: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
  loop:
    - 4646/tcp
    - 4647/tcp
    - 4648/tcp
    - 4648/udp

- name: Create needed directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  loop:
    - /opt/nomad/data/plugins/
    - /opt/cni/bin/

- name: Unarchive CNI
  unarchive:
    src: "{{ cni_archive }}"
    dest: /opt/cni/bin/
    remote_src: true
  notify: Restart Nomad

- name: Copy bridge settings
  copy:
    src: bridge.conf
    dest: /etc/sysctl.d/bridge.conf
    mode: "0644"
  notify: Restart Nomad

- name: "Download and unarchive Podman plguin - {{ podman_plugin_url }}"
  unarchive:
    src: "{{ podman_plugin_url }}"
    dest: /opt/nomad/data/plugins/
    creates: /opt/nomad/data/plugins/nomad-driver-podman
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  notify: Restart Nomad
  # environment:
  #   https_proxy: http://quidproxy.liberty.edu:3128

- name: Add volume dir Nomad
  ansible.builtin.file:
    path: /opt/nomad/data/volumes
    state: directory
    mode: "0755"
  notify: Restart Nomad

- name: Add app dirs Nomad
  ansible.builtin.file:
    path: /opt/nomad/data/volumes/{{ item }}
    state: directory
    mode: "0755"
  notify: Restart Nomad
  loop: "{{ apps }}"

- name: copy Nomad file
  ansible.builtin.template:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
    owner: "nomad"
    group: "nomad"
    mode: "0640"
  notify: Restart Nomad

- name: Start and Enable Nomad
  ansible.builtin.systemd:
    name: nomad
    state: started
    enabled: true
