---
- name: Install nomad
  ansible.builtin.dnf:
    name: nomad
    state: latest

- name: Add Firewall rules for Nomad
  ansible.builtin.firewalld:
    state: "enabled"
    port: "{{ item }}"
    immediate: "yes"
    permanent: "yes"
  loop:
    - 4646/tcp
    - 4647/tcp
    - 4648/tcp
    - 4648/udp

- name: "Download and unarchive Podman plguin - {{ podman_plugin_url }}"
  unarchive:
    src: "{{ podman_plugin_url }}"
    dest: /opt/nomad/data/plugins/
    creates: /opt/nomad/data/plugins/nomad-driver-podman
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  notify: Restart Nomad
  # environment:
  #   https_proxy: http://quidproxy.liberty.edu:3128

- name: Add plugin dir Nomad
  ansible.builtin.file:
    path: /opt/nomad/data/plugins
    state: directory
    mode: "0755"
  notify: Restart Nomad

- name: copy Nomad file
  ansible.builtin.template:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
    owner: "nomad"
    group: "nomad"
    mode: "0640"
  notify: Restart Nomad

- name: Start and Enable Nomad
  ansible.builtin.systemd:
    name: nomad
    state: started
    enabled: true
