---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart Minio Service
  service:
    name: minio
    state: restarted
    enabled: true

- name: Restart redis
  service:
    name: redis
    state: restarted
    enabled: true

- name: Restart sentinel
  service:
    name: redis-sentinel
    state: restarted
    enabled: true

- name: Restart Consul Service
  service:
    name: consul
    state: restarted
    enabled: true
