---
# tasks file for install-servers
- name: Add Hashicorp Repo
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp Repo
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg


- import_tasks: consul.yml
- import_tasks: nomad.yml